feat: table component for sessions
anmode/Move-to-nextJS pull request #809
Opened 2023-11-08 07:45 UTC by rishuraj1

## Related Issue

Closes: #808 

## Description of Changes

- created a table component to handle session data for mentor dashboard
- made it responsive

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/47839626/b57ad78f-4fce-47c0-b7bc-3afb53406db3)

2023-11-08 08:43 UTC, anmode commented
@rishuraj1 is that possible we can stick to Previous UI?? using table component

2023-11-08 08:54 UTC, rishuraj1 commented
@anmode  Yes, okay I will do it now.

2023-11-08 09:41 UTC, rishuraj1 commented
@anmode 

<img width="960" alt="image" src="https://github.com/anmode/grabtern-frontend/assets/47839626/f3c083f5-0f45-4b89-9e5f-7eba5ea23586">

![image](https://github.com/anmode/grabtern-frontend/assets/47839626/3603ba9f-807e-4c00-88f1-5a3e76e0ccab)

2023-11-08 13:50 UTC, anmode commented
Align is not good!  and UI is not same. let me show 
<img width="1280" alt="Screenshot 2023-11-08 at 7 19 07 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/785dd209-23fd-4f66-a2dc-48c5940de6d4">

see the heading is not bold white... and in your UI that is bold white and other is greyish entry!
and rest is fine

2023-11-08 13:51 UTC, anmode requested changes
last thing

2023-11-08 13:51 UTC, anmode commented on components/mentorDashboard/Bookings.js
> +        {/* <ul className="tw-bg-primary-100 tw-text-white  tw-flex tw-items-center tw-gap-6 tw-p-6 tw-border tw-border-b-0 tw-rounded-t">
can you same implement for user dashboard to use this table component in case of bookings please!

2023-11-08 13:55 UTC, rishuraj1 commented on components/mentorDashboard/Bookings.js
> +        {/* <ul className="tw-bg-primary-100 tw-text-white  tw-flex tw-items-center tw-gap-6 tw-p-6 tw-border tw-border-b-0 tw-rounded-t">
yes sure will be done by tomm.

2023-11-08 17:27 UTC, rishuraj1 commented
@anmode  done, 
<img width="960" alt="image" src="https://github.com/anmode/grabtern-frontend/assets/47839626/0ec03845-d328-4369-9468-8817c5d7dbee">

2023-11-09 00:10 UTC, anmode commented
last thing..these heading are in white bold.. please make it normal! as i show in previour UI

2023-11-09 00:14 UTC, anmode commented
One more thing Queries page needs to align properly to use whole space: Need a little designing!
<img width="1201" alt="Screenshot 2023-11-09 at 5 44 06 AM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/800b46f1-d053-4dfd-815a-bddf538efd28">


Rest whole dashboard is awesome now!

2023-11-09 06:35 UTC, rishuraj1 commented
@anmode  
<img width="379" alt="image" src="https://github.com/anmode/grabtern-frontend/assets/47839626/8410b924-6393-4bc1-b866-ebc36f0edca6">

<img width="958" alt="image" src="https://github.com/anmode/grabtern-frontend/assets/47839626/8efe471f-f4a1-44ab-90ba-e8d0015c7e01">

2023-11-09 09:01 UTC, anmode commented
looks cool but color kaise change hogyaa.. I mean theme color was good :)

2023-11-09 09:11 UTC, rishuraj1 commented
@anmode  oops, my bad didn't notice 😅, fixed it now.

2023-11-09 16:05 UTC, anmode commented
> @anmode oops, my bad didn't notice 😅, fixed it now.

no worries i think now it is good to merge this PR! Yeah!!!

2023-11-09 16:05 UTC, merged