fix(twitter-icon): updated twitter icon and fixed unrelated changes
anmode/Move-to-nextJS pull request #860
Opened 2024-10-05 19:16 UTC by Namit2111

## Related Issue

Closes: #837 
Closes: #853 

## Description of Changes

- [ ✔] My code adheres to the established style guidelines of this project.
- [ ✔] I have conducted a self-review of my code.
- [✔ ] I have included comments in areas that may be difficult to understand.
- [✔ ] I have made corresponding updates to the project documentation.
- [✔ ] My changes have not introduced any new warnings.

2024-10-08 04:13 UTC, Sanchitbajaj02 requested changes

2024-10-08 04:13 UTC, Sanchitbajaj02 commented on .gitattributes
What is the need of .gitattributes?

2024-10-08 04:15 UTC, Sanchitbajaj02 commented
Hi @Namit2111 
How is your PR fixes the issue #837 ? Can you give a brief about it?

2024-10-08 08:42 UTC, Namit2111 commented on .gitattributes
It is required to apply the behavior on every system, and it removes the need for locally configuring their Git.

2024-10-08 08:45 UTC, Namit2111 commented
> Hi @Namit2111 How is your PR fixes the issue #837 ? Can you give a brief about it?

The solution sets LF line endings by default for all systems using .gitattributes, preventing automatic conversions caused by OS differences.

The automatic conversion of files was adding files every time in the git history.

2024-10-11 09:13 UTC, Sanchitbajaj02 approved these changes
LGTM

2024-10-11 09:13 UTC, merged